manifest:
  group-filter:
    - +optional
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ldenefle
      url-base: https://github.com/ldenefle

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - cmsis
          - nanopb
          - hal_rpi_pico
          - hal_nordic
    - name: ampoule-protos
      remote: ldenefle
      revision: main
      path: modules/lib/ampoule-protos
