name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.5
    env:
      ZEPHYR_SDK_INSTALL_DIR: "/opt/toolchains/zephyr-sdk-0.16.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make sure repository is linted
        run: |
          clang-format --dry-run --Werror \
            $(find . -type f -name "*.c" -o -name "*.h") \
            2>&1 >/dev/null

      - name: Initialize
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Run twister on unit-tests with qemu_x86
        run: |
          west twister -v \
            -T tests \
            --inline-logs
